### ISSUE TITLE
GEAR 360 MP4 files - Parser Error on XML

### ISSUE THREAD

**Issue by gamersalpha** [google/spatial-media#269]
Hello, 

so i try to use u program but  i m stuck with this error : 

```
stagiaire@srv-web-01:/var/www/html/spatial-media$ sudo python spatialmedia 360_0062\[1\]_Stitch_XHC.MP4
Processing: /var/www/html/spatial-media/360_0062[1]_Stitch_XHC.MP4
Loaded file...
        Track 0
Traceback (most recent call last):
  File "/var/www/html/spatial-media/spatialmedia/../spatialmedia/metadata_utils.py", line 264, in parse_spherical_xml
    parsed_xml = xml.etree.ElementTree.XML(contents)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1312, in XML
    return parser.close()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1671, in close
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: no element found: line 1, column 0


                Parser Error on XML
Traceback (most recent call last):
  File "/var/www/html/spatial-media/spatialmedia/../spatialmedia/metadata_utils.py", line 273, in parse_spherical_xml
    parsed_xml = xml.etree.ElementTree.XML(contents)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1312, in XML
    return parser.close()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1671, in close
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: no element found: line 1, column 0
```

what do u think is wrong please

**Comment by gamersalpha** [comment]
All my video got the error

need help please

![image](https://user-images.githubusercontent.com/32466950/184396162-9f53df4b-ca6d-44e0-a44a-9540add01e3d.png)
