### ISSUE TITLE
Spatial Media Metadata Injector - error - object has no attribute

### ISSUE THREAD

**Issue by kev543210** [google/spatial-media#291]
Hey all, hoping someone can tell me what I’m doing wrong here - trying to inject metadata to allow my 360 footage to be recognised as 360 ‘using 8k file from QooCam 8k’ I had some smaller files working without issue, I’m trying to process a 2 minute 3.9gb file and I get error after opening:

{Traceback (most recent call last):
> File "lib-tk/Tkinter.py", line 1536, in _call
* File "spatialmedia/gui.py", line 63, in action_open
› ( File "spatialmedia/metadata_utils.py", line 388, in parse_metadata
›{ File "spatialmedia/metadata_utils.py", line 343, in parse_mpeg4
›‹ File "spatialmedia/metadata_utils.py", line 311, in parse_spherical_mpeg4
› ( File "spatialmedia/metadata_utils.py", line 261, in parse_spherical_xml
) Afte setrom diasury, heat, is no attribute 'encode"

Is just beyond me what am doing wrong here?
I’m using a iMac to process.

appreciate if someone could point me in right direction :)

**Comment by jamiesonpepper** [comment]
Can you try cloning the current branch and using the command line to perform similar actions and see if it processes as expected?
