### ISSUE TITLE
command line broken since lastest commit

### ISSUE THREAD

**Issue by munwaikong** [google/spatial-media#53]
Hi,

Since the latest commit to master branch, the command line no longer works. Error stacktrace:

Processing: /Users/munwaikong/Desktop/video.mp4
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/munwaikong/Documents/spatial-media/spatialmedia/__main__.py", line 96, in <module>
    main()
  File "/Users/munwaikong/Documents/spatial-media/spatialmedia/__main__.py", line 81, in main
    inject_metadata(args[0], args[1], spherical_xml, console)
  File "/Users/munwaikong/Documents/spatial-media/spatialmedia/../spatialmedia/spherical.py", line 405, in inject_metadata
    if (metadata.audio and extension != ".mp4"):
AttributeError: 'str' object has no attribute 'audio'

It seems that the 'inject_metadata' method is called passing a 'spherical_xml' (string) instead of the new Metadata() object.

**Comment by dcower** [comment]
Thanks for reporting! I've got a fix incoming for this issue that should be in soon.
